# Generated by Django 5.1.1 on 2024-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptoissue",
            name="line_number",
            field=models.IntegerField(),
        ),
    ]
