# Generated by Django 4.2 on 2024-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="html_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="open_issues_count",
            field=models.IntegerField(default=0),
        ),
    ]
