# Generated by Django 4.2 on 2024-12-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_repository_description_repository_html_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="last_analyzed",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="open_issues_count",
        ),
        migrations.AlterField(
            model_name="repository",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
