# Generated by Django 5.1.1 on 2024-11-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_repository_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nvdissue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=10,
            ),
        ),
    ]
