# Generated by Django 5.1.1 on 2024-12-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_cryptoissue_line_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptoissue",
            name="issue_hash",
            field=models.CharField(default="", max_length=64, unique=True),
        ),
    ]
