# Generated by Django 5.1.1 on 2024-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_nvdissue_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_analyzed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="owner",
            field=models.CharField(default="Unknown Owner", max_length=255),
        ),
        migrations.AddField(
            model_name="repository",
            name="stars",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repository",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("analyzing", "Analyzing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
