# Generated by Django 5.1.1 on 2024-11-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_repository_error_message_repository_last_analyzed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
                ("issue_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code_snippet", models.TextField()),
                ("recommendation", models.TextField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.repository",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cve",
            name="nvd_issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.cryptoissue"
            ),
        ),
        migrations.DeleteModel(
            name="NVDIssue",
        ),
    ]
