# Generated by Django 5.1.1 on 2024-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_cryptoissue_checked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoissue",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
