# Generated by Django 5.1.1 on 2024-11-30 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_cryptoissue_alter_cve_nvd_issue_delete_nvdissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoissue",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cryptoissue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cryptoissue",
            name="file_path",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cryptoissue",
            name="issue_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cryptoissue",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="project.repository",
            ),
        ),
    ]
