# Generated by Django 4.2 on 2024-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_repository_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
