# Generated by Django 5.1.1 on 2024-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_cryptoissue_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
