# Generated by Django 5.1.1 on 2024-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_repository_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptoissue",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
