# Generated by Django 5.1.1 on 2024-12-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_cryptoissue_checked_at_cryptoissue_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoissue',
            name='issue_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptoissue',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoissue',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
