# Generated by Django 5.1.1 on 2024-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_cryptoissue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cryptoissue",
            name="code_snippet",
            field=models.TextField(),
        ),
    ]
