# Generated by Django 5.1.1 on 2024-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_repository_visibility_alter_cryptoissue_code_snippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedGitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("html_url", models.URLField()),
                ("open_issues_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
    ]
