# Generated by Django 4.2 on 2024-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_cachedgithubrepository_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedgithubrepository",
            name="owner",
            field=models.CharField(max_length=255),
        ),
    ]
