# Generated by Django 5.1.1 on 2024-12-08 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_alter_repository_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("owner", "name")},
        ),
    ]
