# Generated by Django 5.1.1 on 2024-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0002_profile_delete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
